version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/launcher/main.go
    binary: task-runner-launcher
    flags:
      - -trimpath
    ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips64le
      - ppc64le
      - s390x
      - riscv64
      - loong64
    goarm:
      - 6
      - 7

archives:
  - formats: [ 'tar.gz' ]
    name_template: "{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    files:
      - README.md
      - LICENSE.md
      - LICENSE_EE.md
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

checksum:
  name_template: "{{ .ArtifactName }}.{{ .Algorithm }}"
  algorithm: sha256
  split: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: loong64
    name: task-runner-launcher